name: Fetch

on:
  schedule:
    - cron: "*/5 * * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    name: Fetch stats card img
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fetch
        run: |
          curl "https://github-readme-stats.vercel.app/api?username=sc2013bot&theme=transparent&include_all_commits=true&show_icons=true&bg_color=DEG,FF0000,FFFF00" -Ls -o github-readme-stats_-SONGCI.svg
          curl "https://github-readme-activity-graph.vercel.app/graph?username=sc2013bot&theme=github-compact&hide_border=true&area=true" -Ls -o graph_SONGCI.svg
          curl "https://github-readme-stats.vercel.app/api/top-langs?username=sc2013bot&theme=transparent&include_all_commits=true&show_icons=true&bg_color=DEG,FF0000,FFFF00" -Ls -o top-langs_SONGCI.svg
          echo "$(date '+%Y-%m-%d %H:%M:%S')">upadte_time
          

      - name: Commit & Push
        run: |
          git config --global user.name sc2013bot
          git config --global user.email songci2013@163.com

          git add .

          git commit -m "[${{ github.workflow }}] Upload on $(date '+%Y-%m-%d %H:%M:%S')" || echo 1

          git push
          git push # Attempt
